[platformio]
src_dir = src
include_dir = include

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -Wno-unused-variable
    -Wno-unused-but-set-variable
